//! Go source emitter for wire layouts, constants and fixtures.

use std::fmt::{Display, Write as _};
use std::io::Write as _;
use std::process::{Command, Stdio};

/// Opening of every generated file. The Go package holds both accountants.
const HEADER: &str =
    "// Code generated by svm/accountant/crates/go-codegen. DO NOT EDIT.\n\npackage accountant\n";

pub(crate) fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Go field type of a wire struct. Plain integers are little-endian, as `decodeWire` reads
/// them. `Be*` are the big-endian byte-array types of `solana_wire.go`.
#[derive(Clone, Copy)]
pub(crate) enum GoType {
    U8,
    U16,
    U32,
    U64,
    Be16,
    Be64,
    Bytes(usize),
    Words(usize),
    Wire(&'static str, usize),
}

impl GoType {
    pub(crate) fn size(self) -> usize {
        match self {
            Self::U8 => 1,
            Self::U16 | Self::Be16 => 2,
            Self::U32 => 4,
            Self::U64 | Self::Be64 => 8,
            Self::Bytes(len) => len,
            Self::Words(len) => 4 * len,
            Self::Wire(_, len) => len,
        }
    }

    pub(crate) fn name(self) -> String {
        match self {
            Self::U8 => "uint8".to_owned(),
            Self::U16 => "uint16".to_owned(),
            Self::U32 => "uint32".to_owned(),
            Self::U64 => "uint64".to_owned(),
            Self::Be16 => "be16".to_owned(),
            Self::Be64 => "be64".to_owned(),
            Self::Bytes(len) => format!("[{len}]byte"),
            Self::Words(len) => format!("[{len}]uint32"),
            Self::Wire(name, _) => name.to_owned(),
        }
    }
}

/// One field of a wire struct, with its offset and size in the Rust layout.
pub(crate) struct Field {
    pub(crate) go_name: &'static str,
    pub(crate) ty: GoType,
    pub(crate) offset: usize,
    pub(crate) size: usize,
}

/// A field of a `Zeroable` Rust layout, mapped to a Go type.
macro_rules! field {
    ($layout:ty, $field:ident, $go_name:literal, $ty:expr) => {
        $crate::go::Field {
            go_name: $go_name,
            ty: $ty,
            offset: ::core::mem::offset_of!($layout, $field),
            size: ::core::mem::size_of_val(&<$layout as ::bytemuck::Zeroable>::zeroed().$field),
        }
    };
}
pub(crate) use field;

/// A Go source file. `finish` formats it with gofmt.
pub(crate) struct GoFile(String);

impl GoFile {
    pub(crate) fn new() -> Self {
        Self(HEADER.to_owned())
    }

    pub(crate) fn finish(self) -> String {
        gofmt(&self.0)
    }

    pub(crate) fn section(&mut self, title: &str) {
        write!(self.0, "\n// {title}\n").unwrap();
    }

    pub(crate) fn doc(&mut self, doc: &str) {
        self.0.push('\n');
        if !doc.is_empty() {
            writeln!(self.0, "// {doc}").unwrap();
        }
    }

    pub(crate) fn constant(&mut self, doc: &str, name: &str, value: impl Display) {
        self.doc(doc);
        writeln!(self.0, "const {name} = {value}").unwrap();
    }

    /// One `(doc, name, value)` row per constant.
    pub(crate) fn constants(&mut self, rows: &[(&str, &str, u64)]) {
        for (doc, name, value) in rows {
            self.constant(doc, name, value);
        }
    }

    pub(crate) fn hex_constant(&mut self, doc: &str, name: &str, bytes: &[u8]) {
        self.constant(doc, name, format!("\"{}\"", hex(bytes)));
    }

    pub(crate) fn byte_array(&mut self, doc: &str, name: &str, bytes: &[u8]) {
        let elems: Vec<String> = bytes.iter().map(|b| format!("{b:#04x}")).collect();
        self.doc(doc);
        writeln!(
            self.0,
            "var {name} = [{}]byte{{{}}}",
            bytes.len(),
            elems.join(", ")
        )
        .unwrap();
    }

    /// One `(doc, name, seed)` row per seed. Seeds are ASCII identifiers, so a Go string
    /// literal holds them without escapes.
    pub(crate) fn seeds(&mut self, rows: &[(&str, &str, &[u8])]) {
        for (doc, name, seed) in rows {
            assert!(!seed.is_empty(), "{name} is empty");
            assert!(
                seed.iter().all(|b| b.is_ascii_alphanumeric() || *b == b'_'),
                "{name} needs escaping"
            );
            let text = core::str::from_utf8(seed).expect("ASCII seed");
            self.doc(doc);
            writeln!(self.0, "var {name} = []byte(\"{text}\")").unwrap();
        }
    }

    /// A Go struct with the byte layout of a Rust layout of `len` bytes. `base` is the Rust
    /// offset of the first field. A gap between fields becomes a blank `_` field.
    ///
    /// SECURITY: asserts field order, each field size against its Go type, and the total
    /// length. Thus `binary.Decode` reads every field at its Rust offset.
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn wire_struct(
        &mut self,
        doc: &str,
        name: &str,
        label: &str,
        len_const: &str,
        len: usize,
        base: usize,
        fields: &[Field],
    ) {
        assert!(!fields.is_empty(), "{name} has no fields");
        let mut body = String::new();
        let mut cursor = 0;
        for field in fields {
            let offset = field.offset - base;
            assert!(
                offset >= cursor,
                "{name}.{}: field out of order",
                field.go_name
            );
            assert_eq!(
                field.size,
                field.ty.size(),
                "{name}.{}: Rust size and Go type size differ",
                field.go_name
            );
            if offset > cursor {
                writeln!(body, "\t_ [{}]byte", offset - cursor).unwrap();
            }
            writeln!(body, "\t{} {}", field.go_name, field.ty.name()).unwrap();
            cursor = offset + field.size;
        }
        assert!(cursor <= len, "{name}: fields end past {len}");
        if cursor < len {
            writeln!(body, "\t_ [{}]byte", len - cursor).unwrap();
        }

        self.doc(doc);
        write!(
            self.0,
            "type {name} struct {{\n{body}}}\n\nfunc ({name}) wireLen() int {{ return {len_const} }}\n\nfunc ({name}) wireName() string {{ return \"{label}\" }}\n"
        )
        .unwrap();
    }
}

/// Formats Go source with gofmt, which aligns struct fields.
pub(crate) fn gofmt(source: &str) -> String {
    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap_or_else(|err| panic!("run gofmt: {err}. Put the Go toolchain on PATH."));
    // gofmt reads all input before it writes, so the pipes cannot deadlock.
    child
        .stdin
        .take()
        .expect("piped stdin")
        .write_all(source.as_bytes())
        .expect("write gofmt stdin");
    let output = child.wait_with_output().expect("wait for gofmt");
    assert!(
        output.status.success(),
        "gofmt: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("gofmt output is UTF-8")
}

/// Lossless widening of a layout size or offset.
pub(crate) fn n(value: usize) -> u64 {
    value as u64
}
