//! Mainnet NTT parity test.
//!
//! Replays signed NTT VAAs — pulled from wormholescan for transfers the
//! wormchain NTT global-accountant actually committed (mainnet height
//! 18,669,029) — through the program's parsing + hub-substitution logic, and
//! checks the result against what the contract committed. The corpus
//! (`fixtures/ntt_test_vectors.json`) is regenerated by `fetch_test_vectors.py`;
//! see that script for provenance.
//!
//! Per vector this asserts, on real bytes:
//!   1. `keccak256(keccak256(body))` equals the digest the contract stored
//!      (we fetched the right VAA; the digest scheme matches).
//!   2. Relayer-vs-direct dispatch matches reality: relayer-delivered VAAs are a
//!      `DeliveryInstruction` wrapping the `TransceiverMessage`; the rest carry
//!      the `TransceiverMessage` directly.
//!   3. Hub substitution: the hub registered for `(emitter_chain, sender)` — the
//!      same key the program uses — gives the committed `(token_chain,
//!      token_address)`. `sender` is the relayer-unwrapped sender, or the emitter
//!      for a direct transfer.
//!   4. `parse_ntt_transfer` yields the committed normalized amount and recipient
//!      chain.
//!
//! On-chain balance-write mechanics (PDA mutation, quorum accumulation) are not
//! exercised here — those are covered by `tests/submit_observations.rs`.

use std::collections::HashMap;

use global_accountant_definitions::{parse_delivery_instruction, parse_ntt_transfer, Uint256};
use serde_json::Value;

/// `keccak256(keccak256(body))` — the VAA digest, host-side.
fn double_keccak256(body: &[u8]) -> [u8; 32] {
    let inner = solana_keccak_hasher::hashv(&[body]).to_bytes();
    solana_keccak_hasher::hashv(&[&inner]).to_bytes()
}

fn hex_bytes(s: &str) -> Vec<u8> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex byte"))
        .collect()
}

fn hex32(s: &str) -> [u8; 32] {
    let v = hex_bytes(s);
    let mut a = [0u8; 32];
    a.copy_from_slice(&v);
    a
}

fn u16_field(v: &Value, k: &str) -> u16 {
    v[k].as_u64().unwrap_or_else(|| panic!("field {k}")) as u16
}

#[test]
fn mainnet_vectors_match_committed_accounting() {
    let corpus: Value =
        serde_json::from_str(include_str!("fixtures/ntt_test_vectors.json")).expect("parse corpus");

    // Hub token-identity registry, keyed by (chain, transceiver address) exactly
    // as the program keys the TransceiverHub PDA.
    let mut hubs: HashMap<(u16, [u8; 32]), (u16, [u8; 32])> = HashMap::new();
    for h in corpus["hubs"].as_array().expect("hubs") {
        hubs.insert(
            (u16_field(h, "chain"), hex32(h["address"].as_str().unwrap())),
            (
                u16_field(h, "hub_chain"),
                hex32(h["hub_address"].as_str().unwrap()),
            ),
        );
    }

    let vectors = corpus["vectors"].as_array().expect("vectors");
    assert!(vectors.len() >= 28, "expected the full corpus, got {}", vectors.len());

    let (mut relayer, mut direct) = (0usize, 0usize);
    for v in vectors {
        let chain = u16_field(v, "chain");
        let seq = v["sequence"].as_u64().expect("sequence");
        let label = format!("chain={chain} seq={seq}");

        // Strip the VAA header (6 + 66*num_sigs) to reach the signed body.
        let vaa = hex_bytes(v["vaa_hex"].as_str().expect("vaa_hex"));
        let num_sigs = vaa[5] as usize;
        let body = &vaa[6 + 66 * num_sigs..];

        // (1) Digest parity.
        assert_eq!(
            double_keccak256(body),
            hex32(v["expected_digest"].as_str().expect("expected_digest")),
            "[{label}] keccak256(keccak256(body)) must equal the committed digest"
        );

        // VAA body header is 51 bytes; the payload follows.
        let payload = &body[51..];
        let emitter = hex32(v["emitter"].as_str().expect("emitter"));

        // (2)+(3 prep) Dispatch exactly as the program does, resolving `sender`.
        let (sender, ntt_payload): ([u8; 32], &[u8]) =
            if v["via_relayer"].as_bool().expect("via_relayer") {
                relayer += 1;
                let unwrap = parse_delivery_instruction(payload)
                    .unwrap_or_else(|e| panic!("[{label}] parse_delivery_instruction: {e:?}"));
                (unwrap.sender, unwrap.inner_payload)
            } else {
                direct += 1;
                (emitter, payload)
            };

        // (3) Hub substitution: the hub for (chain, sender) is the committed
        // token identity — never the NTT message's source_token.
        let hub = hubs
            .get(&(chain, sender))
            .unwrap_or_else(|| panic!("[{label}] no hub registered for (chain, sender)"));
        assert_eq!(
            *hub,
            (
                u16_field(v, "expected_token_chain"),
                hex32(v["expected_token_address"].as_str().expect("expected_token_address")),
            ),
            "[{label}] hub-substituted token identity mismatch"
        );

        // (4) Parse + normalize.
        let transfer = parse_ntt_transfer(ntt_payload)
            .unwrap_or_else(|e| panic!("[{label}] parse_ntt_transfer: {e:?}"));
        assert_eq!(
            transfer.amount,
            Uint256::from_be_bytes(hex32(v["expected_amount"].as_str().expect("expected_amount"))),
            "[{label}] normalized amount mismatch"
        );
        assert_eq!(
            transfer.recipient_chain,
            u16_field(v, "expected_recipient_chain"),
            "[{label}] recipient_chain mismatch"
        );
    }

    assert!(
        relayer > 0 && direct > 0,
        "corpus must cover both relayer-wrapped and direct shapes (got {relayer} relayer, {direct} direct)"
    );
    eprintln!("[test-vectors] {relayer} relayer-wrapped, {direct} direct — all match committed accounting");
}
