//! Generates the layout constants and test fixtures of `node/pkg/accountant` from the
//! program types and code paths. Fails when a checked-in Go file differs.
//!
//! `just go-codegen` writes the files. `just test` checks them.

use core::mem::{offset_of, size_of_val};
use std::fmt::{Display, Write as _};
use std::path::{Path, PathBuf};

use accountant_operational_core::cpi::noreplay::derive_bucket_pda;
use accountant_operational_core::support::quorum::derive_pending_pda;
use accountant_test_fixtures::{Vaa, MAINNET_OTHER_SEQ2211, MAINNET_TRANSFER_SEQ1395207};
use bytemuck::Zeroable;
use global_accountant_definitions::{
    AccountantDigestLog, GlobalAccountantError, Instruction, NoReplayBitmapAccount,
    PendingObservationsLayout, SubmitObservationsIxData, TokenBridgeTransfer, TxId, VaaBodyHeader,
    ACCOUNTANT_DIGEST_LOG_TAG, ACCOUNT_SEED_PREFIX, CHAIN_REGISTRATION_SEED_PREFIX,
    GUARDIAN_SET_SEED, HASH_TX_ID_LEN, MAX_TRANSFER_PAYLOAD_LEN, NOREPLAY_AUTHORITY_SEED_PREFIX,
    NOREPLAY_BITS_PER_BUCKET, PENDING_OBSERVATIONS_SEED_PREFIX, SIGNATURE_TX_ID_LEN,
};
use solana_pubkey::Pubkey;

mod common;
use common::{
    content_digest, noreplay_authority_pda, observation_ix_from_body, signing_digest_with_tx_id,
    submit_observations_ix_data_with_tx_id,
};

/// Repository root is four levels above this crate.
const GO_PACKAGE_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../../node/pkg/accountant"
);
const LAYOUT_FILE: &str = "solana_layout_gen.go";
const FIXTURES_FILE: &str = "solana_layout_fixtures_gen_test.go";
const WRITE_ENV: &str = "GO_CODEGEN_WRITE";

/// The program dispatches on one `u8` discriminator before the instruction data.
const DISPATCH_LEN: usize = 1;

/// Start of the hashed record: the tail of `SubmitObservationsIxData` from `action`.
/// `real_vectors` asserts that the tail equals `fields_and_digest()`.
const FIELDS_START: usize = offset_of!(SubmitObservationsIxData, action);

/// Guardian set of the mainnet fixture VAAs.
const MAINNET_GUARDIAN_SET: u32 = 6;

/// Guardian indices covering every word of the 128-bit bitmap.
const SET_BITS: [u8; 6] = [0, 3, 5, 33, 64, 127];

/// Fields and content digests exclude the tx id. Thus the real-data vectors use a zero tx id.
const ZERO_TX_ID: TxId<'static> = TxId::Hash(&[0u8; 32]);

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// A Go source file. Each declaration is its own statement, so the output is gofmt-formatted.
struct GoFile(String);

impl GoFile {
    fn new() -> Self {
        Self(
            "// Code generated by svm/accountant/programs/global-accountant/tests/go_codegen.rs. DO NOT EDIT.\n\npackage accountant\n"
                .to_owned(),
        )
    }

    fn finish(self) -> String {
        self.0
    }

    fn section(&mut self, title: &str) {
        write!(self.0, "\n// {title}\n").unwrap();
    }

    fn doc(&mut self, doc: &str) {
        self.0.push('\n');
        if !doc.is_empty() {
            writeln!(self.0, "// {doc}").unwrap();
        }
    }

    fn constant(&mut self, doc: &str, name: &str, value: impl Display) {
        self.doc(doc);
        writeln!(self.0, "const {name} = {value}").unwrap();
    }

    /// One `(doc, name, value)` row per constant.
    fn constants(&mut self, rows: &[(&str, &str, u64)]) {
        for (doc, name, value) in rows {
            self.constant(doc, name, value);
        }
    }

    fn hex_constant(&mut self, doc: &str, name: &str, bytes: &[u8]) {
        self.constant(doc, name, format!("\"{}\"", hex(bytes)));
    }

    fn byte_array(&mut self, doc: &str, name: &str, bytes: &[u8]) {
        let elems: Vec<String> = bytes.iter().map(|b| format!("{b:#04x}")).collect();
        self.doc(doc);
        writeln!(
            self.0,
            "var {name} = [{}]byte{{{}}}",
            bytes.len(),
            elems.join(", ")
        )
        .unwrap();
    }

    /// One `(doc, name, seed)` row per seed. Seeds are ASCII identifiers, so a Go string
    /// literal holds them without escapes.
    fn seeds(&mut self, rows: &[(&str, &str, &[u8])]) {
        for (doc, name, seed) in rows {
            assert!(!seed.is_empty(), "{name} is empty");
            assert!(
                seed.iter().all(|b| b.is_ascii_alphanumeric() || *b == b'_'),
                "{name} needs escaping"
            );
            let text = core::str::from_utf8(seed).expect("ASCII seed");
            self.doc(doc);
            writeln!(self.0, "var {name} = []byte(\"{text}\")").unwrap();
        }
    }
}

/// Lossless widening of a layout size or offset.
fn n(value: usize) -> u64 {
    value as u64
}

fn layout_file() -> String {
    let mut go = GoFile::new();

    go.section("AccountantDigestLog, constants/log.rs.");
    go.constant(
        "AccountantDigestLog::LEN.",
        "accountantDigestLogLen",
        AccountantDigestLog::LEN,
    );
    go.byte_array(
        "ACCOUNTANT_DIGEST_LOG_TAG.",
        "accountantDigestLogTag",
        &ACCOUNTANT_DIGEST_LOG_TAG,
    );
    go.constants(&[
        (
            "Big-endian.",
            "accountantDigestLogChainOffset",
            n(offset_of!(AccountantDigestLog, chain)),
        ),
        (
            "",
            "accountantDigestLogEmitterOffset",
            n(offset_of!(AccountantDigestLog, emitter)),
        ),
        (
            "Big-endian.",
            "accountantDigestLogSequenceOffset",
            n(offset_of!(AccountantDigestLog, sequence)),
        ),
        (
            "",
            "accountantDigestLogDigestOffset",
            n(offset_of!(AccountantDigestLog, digest)),
        ),
        (
            "Little-endian.",
            "accountantDigestLogGuardianSetIndexOffset",
            n(offset_of!(AccountantDigestLog, guardian_set_index)),
        ),
    ]);

    go.section("PendingObservationsLayout, state.rs. Integers are little-endian.");
    go.constants(&[
        (
            "PendingObservationsLayout::LEN.",
            "pendingObservationsLen",
            n(PendingObservationsLayout::LEN),
        ),
        (
            "PendingObservationsLayout::TAG.",
            "pendingObservationsTag",
            u64::from(PendingObservationsLayout::TAG),
        ),
        (
            "PendingObservationsLayout::MAX_GUARDIANS.",
            "pendingObservationsMaxGuardians",
            u64::from(PendingObservationsLayout::MAX_GUARDIANS),
        ),
        (
            "u32 words in the signature bitmap.",
            "pendingObservationsSignatureWords",
            n(PendingObservationsLayout::zeroed().signatures.len()),
        ),
        (
            "",
            "pendingObservationsChainOffset",
            n(offset_of!(PendingObservationsLayout, chain)),
        ),
        (
            "",
            "pendingObservationsGuardianSetIndexOffset",
            n(offset_of!(PendingObservationsLayout, guardian_set_index)),
        ),
        (
            "",
            "pendingObservationsSignaturesOffset",
            n(offset_of!(PendingObservationsLayout, signatures)),
        ),
        (
            "",
            "pendingObservationsContentDigestOffset",
            n(offset_of!(PendingObservationsLayout, content_digest)),
        ),
        (
            "",
            "pendingObservationsPayerOffset",
            n(offset_of!(PendingObservationsLayout, payer)),
        ),
    ]);

    go.section("solana-noreplay bucket, constants/noreplay.rs.");
    go.constants(&[
        (
            "NoReplayBitmapAccount::LEN.",
            "noreplayBucketLen",
            n(NoReplayBitmapAccount::LEN),
        ),
        (
            "",
            "noreplayBitmapOffset",
            n(offset_of!(NoReplayBitmapAccount, bitmap)),
        ),
        (
            "NOREPLAY_BITS_PER_BUCKET.",
            "noreplayBitsPerBucket",
            NOREPLAY_BITS_PER_BUCKET,
        ),
    ]);

    assert_eq!(
        size_of_val(&SubmitObservationsIxData::zeroed().tx_id),
        SIGNATURE_TX_ID_LEN
    );
    go.section(
        "submit_observations instruction data, ix_data.rs. Offsets include the discriminator.",
    );
    go.constants(&[
        (
            "One u8 discriminator.",
            "submitObservationsDispatchLen",
            n(DISPATCH_LEN),
        ),
        (
            "Instruction::SubmitObservations.",
            "submitObservationsDiscriminator",
            u64::from(Instruction::SubmitObservations as u8),
        ),
        (
            "SubmitObservationsIxData::LEN.",
            "submitObservationsIxDataLen",
            n(SubmitObservationsIxData::LEN),
        ),
        (
            "Little-endian.",
            "submitGuardianSetIndexOffset",
            n(DISPATCH_LEN + offset_of!(SubmitObservationsIxData, guardian_set_index)),
        ),
        (
            "",
            "submitGuardianIndexOffset",
            n(DISPATCH_LEN + offset_of!(SubmitObservationsIxData, guardian_index)),
        ),
        (
            "",
            "submitSignatureOffset",
            n(DISPATCH_LEN + offset_of!(SubmitObservationsIxData, signature)),
        ),
        (
            "r ‖ s ‖ recovery_id.",
            "submitSignatureLen",
            n(size_of_val(&SubmitObservationsIxData::zeroed().signature)),
        ),
        (
            "",
            "submitTxIDLenOffset",
            n(DISPATCH_LEN + offset_of!(SubmitObservationsIxData, tx_id_len)),
        ),
        (
            "",
            "submitTxIDOffset",
            n(DISPATCH_LEN + offset_of!(SubmitObservationsIxData, tx_id)),
        ),
        (
            "Start of the hashed record.",
            "submitFieldsOffset",
            n(DISPATCH_LEN + FIELDS_START),
        ),
    ]);

    go.section("TxId, ix_data.rs.");
    go.constants(&[
        ("HASH_TX_ID_LEN.", "hashTxIDLen", n(HASH_TX_ID_LEN)),
        (
            "SIGNATURE_TX_ID_LEN.",
            "signatureTxIDLen",
            n(SIGNATURE_TX_ID_LEN),
        ),
    ]);

    go.section("ObservationFieldsAndDigest, ix_data.rs. Integers are big-endian.");
    go.constants(&[
        (
            "Length of the hashed record.",
            "observationFieldsLen",
            n(SubmitObservationsIxData::LEN - FIELDS_START),
        ),
        (
            "",
            "fieldsActionOffset",
            n(offset_of!(SubmitObservationsIxData, action) - FIELDS_START),
        ),
        (
            "",
            "fieldsChainOffset",
            n(offset_of!(SubmitObservationsIxData, chain) - FIELDS_START),
        ),
        (
            "",
            "fieldsEmitterOffset",
            n(offset_of!(SubmitObservationsIxData, emitter) - FIELDS_START),
        ),
        (
            "",
            "fieldsSequenceOffset",
            n(offset_of!(SubmitObservationsIxData, sequence) - FIELDS_START),
        ),
        (
            "",
            "fieldsTokenChainOffset",
            n(offset_of!(SubmitObservationsIxData, token_chain) - FIELDS_START),
        ),
        (
            "",
            "fieldsTokenAddressOffset",
            n(offset_of!(SubmitObservationsIxData, token_address) - FIELDS_START),
        ),
        (
            "",
            "fieldsRecipientChainOffset",
            n(offset_of!(SubmitObservationsIxData, recipient_chain) - FIELDS_START),
        ),
        (
            "",
            "fieldsAmountOffset",
            n(offset_of!(SubmitObservationsIxData, amount) - FIELDS_START),
        ),
        (
            "",
            "fieldsVaaDigestOffset",
            n(offset_of!(SubmitObservationsIxData, digest) - FIELDS_START),
        ),
    ]);

    go.section("Token Bridge transfer payload, vaa.rs.");
    go.constants(&[
        (
            "TokenBridgeTransfer::LEN.",
            "tokenBridgeTransferLen",
            n(TokenBridgeTransfer::LEN),
        ),
        (
            "MAX_TRANSFER_PAYLOAD_LEN.",
            "maxTransferPayloadLen",
            n(MAX_TRANSFER_PAYLOAD_LEN),
        ),
    ]);

    go.section("PDA seed prefixes, constants/seeds.rs.");
    go.seeds(&[
        (
            "PENDING_OBSERVATIONS_SEED_PREFIX.",
            "pendingObservationsSeedPrefix",
            PENDING_OBSERVATIONS_SEED_PREFIX,
        ),
        (
            "NOREPLAY_AUTHORITY_SEED_PREFIX.",
            "noreplayAuthoritySeedPrefix",
            NOREPLAY_AUTHORITY_SEED_PREFIX,
        ),
        (
            "ACCOUNT_SEED_PREFIX.",
            "balanceAccountSeedPrefix",
            ACCOUNT_SEED_PREFIX,
        ),
        (
            "CHAIN_REGISTRATION_SEED_PREFIX.",
            "chainRegistrationSeedPrefix",
            CHAIN_REGISTRATION_SEED_PREFIX,
        ),
        (
            "GUARDIAN_SET_SEED. The Core Bridge's own seed.",
            "guardianSetSeedPrefix",
            GUARDIAN_SET_SEED,
        ),
    ]);

    go.section("GlobalAccountantError codes returned as ProgramError::Custom, error.rs.");
    for (name, code) in [
        (
            "solanaErrPayerMismatch",
            GlobalAccountantError::PayerMismatch,
        ),
        (
            "solanaErrAlreadyAccounted",
            GlobalAccountantError::AlreadyAccounted,
        ),
        (
            "solanaErrInvalidSignature",
            GlobalAccountantError::InvalidSignature,
        ),
        (
            "solanaErrInvalidGuardianIndex",
            GlobalAccountantError::InvalidGuardianIndex,
        ),
        (
            "solanaErrAlreadySigned",
            GlobalAccountantError::AlreadySigned,
        ),
        (
            "solanaErrExpiredGuardianSet",
            GlobalAccountantError::ExpiredGuardianSet,
        ),
        (
            "solanaErrMissingChainRegistration",
            GlobalAccountantError::MissingChainRegistration,
        ),
        (
            "solanaErrUnregisteredEmitter",
            GlobalAccountantError::UnregisteredEmitter,
        ),
    ] {
        go.constant(
            &format!("GlobalAccountantError::{code:?}."),
            name,
            u32::from(code),
        );
    }

    go.finish()
}

/// Writes the real-data vectors of one fixture VAA, named `fixture<label>*`, and returns its
/// header. The fields exclude the guardian set, so the vectors use set 0.
fn real_vectors(go: &mut GoFile, label: &str, vaa: &Vaa) -> VaaBodyHeader {
    let body = vaa.body();
    let ix = observation_ix_from_body(0, 0, [0u8; 65], ZERO_TX_ID, body);
    let fields = ix.fields_and_digest();
    assert_eq!(
        &bytemuck::bytes_of(&ix)[FIELDS_START..],
        fields.as_slice(),
        "{label}: the hashed record is the instruction data tail"
    );

    let (header, _payload) = VaaBodyHeader::split(body).expect("fixture has a valid VAA header");
    go.hex_constant("", &format!("fixture{label}BodyHex"), body);
    go.hex_constant(
        "",
        &format!("fixture{label}EmitterHex"),
        &header.emitter_address,
    );
    go.hex_constant("", &format!("fixture{label}VaaDigestHex"), &ix.digest);
    go.hex_constant("", &format!("fixture{label}FieldsHex"), &fields);
    go.hex_constant(
        "",
        &format!("fixture{label}ContentDigestHex"),
        &content_digest(body),
    );
    go.constant(
        "",
        &format!("fixture{label}Sequence"),
        format!("uint64({})", header.sequence()),
    );
    *header
}

fn fixtures_file() -> String {
    // The hex fixtures below embed these lengths.
    assert_eq!(PendingObservationsLayout::LEN, 88);
    assert_eq!(SubmitObservationsIxData::LEN, 278);
    assert_eq!(AccountantDigestLog::LEN, 86);

    // Index-derived bytes make byte-order bugs in the Go decoder visible.
    let program_id_bytes: [u8; 32] = core::array::from_fn(|i| i as u8);
    let program_id = Pubkey::new_from_array(program_id_bytes);
    let emitter: [u8; 32] = core::array::from_fn(|i| 0x40 + i as u8);
    let digest: [u8; 32] = core::array::from_fn(|i| 0x80 + i as u8);
    let payer: [u8; 32] = core::array::from_fn(|i| 0xC0 + i as u8);
    let signature: [u8; 65] = core::array::from_fn(|i| i as u8);
    let hash_tx_id: [u8; 32] = core::array::from_fn(|i| 0xE0 + i as u8);
    let signature_tx_id: [u8; 64] = core::array::from_fn(|i| 0xA0 + i as u8);
    let chain: u16 = 2;
    let sequence: u64 = 100_000;
    let guardian_set_index: u32 = 4;
    let guardian_index: u8 = 3;

    let mut go = GoFile::new();
    go.constant(
        "VaaBodyHeader::LEN, vaa.rs. The payload follows it.",
        "fixtureVaaBodyHeaderLen",
        VaaBodyHeader::LEN,
    );

    go.section(
        "Index-derived vectors: program id 0x00.., emitter 0x40.., digest 0x80.., payer 0xC0...",
    );
    let mut pending = PendingObservationsLayout::new(chain, guardian_set_index, digest, payer);
    for index in SET_BITS {
        pending
            .set_signature(index)
            .expect("index below MAX_GUARDIANS");
    }
    assert_eq!(pending.num_signatures(), SET_BITS.len() as u32);
    let pending_bytes = bytemuck::bytes_of(&pending);
    assert_eq!(pending_bytes.len(), PendingObservationsLayout::LEN);
    go.hex_constant(
        "Chain 2, set index 4, bits 0, 3, 5, 33, 64 and 127.",
        "fixturePendingObservationsAccountHex",
        pending_bytes,
    );

    let noreplay_authority = noreplay_authority_pda(&program_id);
    go.hex_constant(
        "",
        "fixtureNoreplayAuthorityPDAHex",
        noreplay_authority.as_array(),
    );

    // Sequences 1023 and 1024 straddle a bucket boundary.
    let boundary_chain: u16 = 56;
    let (bucket_1023, _) = derive_bucket_pda(&noreplay_authority, boundary_chain, &emitter, 1023);
    let (bucket_1024, _) = derive_bucket_pda(&noreplay_authority, boundary_chain, &emitter, 1024);
    assert_ne!(
        bucket_1023.as_array(),
        bucket_1024.as_array(),
        "sequence 1023 and 1024 must fall in different buckets"
    );
    go.hex_constant(
        "Chain 56, sequence 1023.",
        "fixtureNoreplayBucketPDASeq1023Hex",
        bucket_1023.as_array(),
    );
    go.hex_constant(
        "Chain 56, sequence 1024.",
        "fixtureNoreplayBucketPDASeq1024Hex",
        bucket_1024.as_array(),
    );

    let commit_log = AccountantDigestLog::new(chain, emitter, sequence, digest, guardian_set_index);
    assert_eq!(commit_log.as_bytes().len(), AccountantDigestLog::LEN);
    go.hex_constant(
        "Chain 2, sequence 100000, set index 4.",
        "fixtureACCDGSTLogHex",
        commit_log.as_bytes(),
    );

    go.section(&format!(
        "Mainnet Solana Token Bridge transfer, sequence 1395207, guardian set {MAINNET_GUARDIAN_SET}."
    ));
    let transfer_body = MAINNET_TRANSFER_SEQ1395207.body();
    let transfer_header = real_vectors(&mut go, "Transfer", &MAINNET_TRANSFER_SEQ1395207);
    let (transfer_pending_pda, _) = derive_pending_pda(
        &program_id,
        transfer_header.emitter_chain(),
        &transfer_header.emitter_address,
        transfer_header.sequence(),
        MAINNET_GUARDIAN_SET,
        &content_digest(transfer_body),
    );
    go.hex_constant(
        "",
        "fixtureTransferPendingPDAHex",
        transfer_pending_pda.as_array(),
    );
    go.constant(
        "",
        "fixtureTransferGuardianSetIndex",
        format!("uint32({MAINNET_GUARDIAN_SET})"),
    );

    go.section("Mainnet Solana Token Bridge message with non-transfer action 0x99, sequence 2211.");
    real_vectors(&mut go, "Other", &MAINNET_OTHER_SEQ2211);

    go.section("submit_observations data for the transfer body, guardian set 4, guardian index 3.");
    let hash = TxId::Hash(&hash_tx_id);
    let sig = TxId::Signature(&signature_tx_id);
    let submit_data = |tx_id| {
        let data = submit_observations_ix_data_with_tx_id(
            guardian_set_index,
            guardian_index,
            signature,
            tx_id,
            transfer_body,
        );
        assert_eq!(data.len(), DISPATCH_LEN + SubmitObservationsIxData::LEN);
        data
    };
    go.hex_constant(
        "32-byte tx id.",
        "fixtureSubmitObservationsIxDataHex",
        &submit_data(hash),
    );
    go.hex_constant("", "fixtureSubmitObservationsTxIDHex", &hash_tx_id);
    go.hex_constant(
        "64-byte tx id.",
        "fixtureSubmitObservationsSignatureTxIDIxDataHex",
        &submit_data(sig),
    );
    go.hex_constant(
        "",
        "fixtureSubmitObservationsSignatureTxIDHex",
        &signature_tx_id,
    );

    go.section(
        "What each guardian signs for the transfer above: keccak256(prefix ‖ tx_id ‖ fields).",
    );
    go.hex_constant(
        "32-byte tx id.",
        "fixtureTransferSigningDigestHex",
        &signing_digest_with_tx_id(hash, transfer_body),
    );
    go.hex_constant(
        "64-byte tx id.",
        "fixtureTransferSignatureTxIDSigningDigestHex",
        &signing_digest_with_tx_id(sig, transfer_body),
    );

    go.finish()
}

/// Writes `contents` to `path` when `GO_CODEGEN_WRITE=1`. Otherwise requires the checked-in
/// file to equal `contents`.
fn write_or_check(path: &Path, contents: &str) {
    if std::env::var(WRITE_ENV).as_deref() == Ok("1") {
        std::fs::write(path, contents)
            .unwrap_or_else(|err| panic!("write {}: {err}", path.display()));
    } else {
        let checked_in = std::fs::read_to_string(path)
            .unwrap_or_else(|err| panic!("read {}: {err}. Run `just go-codegen`.", path.display()));
        // Exact bytes: a line-ending change is drift too.
        if checked_in != contents {
            panic!("{}", first_difference(path, &checked_in, contents));
        }
    }
}

/// Describes the first differing line. Hex lines are long, so each side is truncated.
fn first_difference(path: &Path, checked_in: &str, generated: &str) -> String {
    const SHOWN: usize = 120;
    let old: Vec<&str> = checked_in.split('\n').collect();
    let new: Vec<&str> = generated.split('\n').collect();
    let show = |side: Option<&&str>| match side {
        Some(text) => text.chars().take(SHOWN).collect::<String>(),
        None => "<end of file>".to_owned(),
    };
    for i in 0..old.len().max(new.len()) {
        if old.get(i) != new.get(i) {
            return format!(
                "{} differs from the program at line {}.\n  checked in: {}\n  generated:  {}\nRun `just go-codegen`.",
                path.display(),
                i + 1,
                show(old.get(i)),
                show(new.get(i)),
            );
        }
    }
    unreachable!("the files differ, so one line differs");
}

#[test]
fn go_files_match_program() {
    let dir = PathBuf::from(GO_PACKAGE_DIR);
    write_or_check(&dir.join(LAYOUT_FILE), &layout_file());
    write_or_check(&dir.join(FIXTURES_FILE), &fixtures_file());
}
