FROM rust:1.85.1-slim@sha256:9f841bbe9e7d8e37ceb96ed907265a3a0df7f44e3737d0b100e7907a679acb36 AS sui-build

# https://github.com/MystenLabs/sui/blob/cd58464d654d43c23d3615d69826bf1a58ce61c3/docs/content/guides/developer/getting-started/sui-install.mdx#all-linux-prerequisites
RUN apt-get update && \
    apt-get install -y curl git-all cmake gcc libssl-dev pkg-config libclang-dev libpq-dev build-essential && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*.

# https://github.com/MystenLabs/sui/releases/tag/mainnet-v1.52.3
RUN cargo install --locked --git https://github.com/MystenLabs/sui.git --rev cd58464d654d43c23d3615d69826bf1a58ce61c3 sui

FROM rust:1.85.1-slim@sha256:9f841bbe9e7d8e37ceb96ed907265a3a0df7f44e3737d0b100e7907a679acb36 AS sui-node-base
WORKDIR /tmp

RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*.
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

ARG NODE_MAJOR=18
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update && \
    apt-get install -y nodejs && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*.


FROM sui-node-base AS sui-node

COPY --from=sui-build /usr/local/cargo/bin/sui /bin/sui
