// Code generated by svm/accountant/crates/go-codegen. DO NOT EDIT.

package accountant

// AccountantDigestLog, constants/log.rs.

// AccountantDigestLog::LEN.
const accountantDigestLogLen = 86

// ACCOUNTANT_DIGEST_LOG_TAG.
var accountantDigestLogTag = [8]byte{0x41, 0x43, 0x43, 0x44, 0x47, 0x53, 0x54, 0x00}

// accountantDigestLogWire is AccountantDigestLog.
type accountantDigestLogWire struct {
	Tag              [8]byte
	Chain            be16
	Emitter          [32]byte
	Sequence         be64
	Digest           [32]byte
	GuardianSetIndex uint32
}

func (accountantDigestLogWire) wireLen() int { return accountantDigestLogLen }

func (accountantDigestLogWire) wireName() string { return "accountant digest log" }

// PendingObservationsLayout, state.rs.

// PendingObservationsLayout::LEN.
const pendingObservationsLen = 88

// PendingObservationsLayout::TAG.
const pendingObservationsTag = 1

// PendingObservationsLayout::MAX_GUARDIANS.
const pendingObservationsMaxGuardians = 128

// u32 words in the signature bitmap.
const pendingObservationsSignatureWords = 4

// pendingObservationsWire is PendingObservationsLayout.
type pendingObservationsWire struct {
	Tag              uint8
	_                [1]byte
	Chain            uint16
	GuardianSetIndex uint32
	Signatures       [4]uint32
	ContentDigest    [32]byte
	Payer            [32]byte
}

func (pendingObservationsWire) wireLen() int { return pendingObservationsLen }

func (pendingObservationsWire) wireName() string { return "pending observations account" }

// solana-noreplay, constants/noreplay.rs.

// NoReplayBitmapAccount::LEN.
const noreplayBucketLen = 129

// NOREPLAY_BITS_PER_BUCKET.
const noreplayBitsPerBucket = 1024

// NoReplayNamespace::LEN.
const noreplayNamespaceLen = 34

// NoReplayNamespace::seed_chunks split point.
const noreplayNamespaceSeedSplit = 32

// noreplayBucketWire is NoReplayBitmapAccount.
type noreplayBucketWire struct {
	Bump   uint8
	Bitmap [128]byte
}

func (noreplayBucketWire) wireLen() int { return noreplayBucketLen }

func (noreplayBucketWire) wireName() string { return "noreplay bucket account" }

// noreplayNamespaceWire is NoReplayNamespace.
type noreplayNamespaceWire struct {
	Chain   be16
	Emitter [32]byte
}

func (noreplayNamespaceWire) wireLen() int { return noreplayNamespaceLen }

func (noreplayNamespaceWire) wireName() string { return "noreplay namespace" }

// ObservationFieldsAndDigest, ix_data.rs: the hashed record.

// Length of the hashed record.
const observationFieldsLen = 143

// observationFieldsWire is the tail of SubmitObservationsIxData from action.
type observationFieldsWire struct {
	Action         uint8
	Chain          be16
	Emitter        [32]byte
	Sequence       be64
	TokenChain     be16
	TokenAddress   [32]byte
	RecipientChain be16
	Amount         [32]byte
	VaaDigest      [32]byte
}

func (observationFieldsWire) wireLen() int { return observationFieldsLen }

func (observationFieldsWire) wireName() string { return "observation fields" }

// submit_observations instruction, ix_data.rs.

// Instruction::SubmitObservations.
const submitObservationsDiscriminator = 0

// SubmitObservationsIxData::LEN.
const submitObservationsIxDataLen = 278

// One u8 discriminator plus the data.
const submitObservationsInstructionLen = 279

// r ‖ s ‖ recovery_id.
const submitSignatureLen = 65

// HASH_TX_ID_LEN.
const hashTxIDLen = 32

// SIGNATURE_TX_ID_LEN.
const signatureTxIDLen = 64

// submitObservationsIxDataWire is SubmitObservationsIxData.
type submitObservationsIxDataWire struct {
	GuardianSetIndex uint32
	GuardianIndex    uint8
	Signature        [65]byte
	TxIDLen          uint8
	TxID             [64]byte
	Fields           observationFieldsWire
}

func (submitObservationsIxDataWire) wireLen() int { return submitObservationsIxDataLen }

func (submitObservationsIxDataWire) wireName() string { return "submit_observations instruction data" }

// submitObservationsInstructionWire is the discriminator and SubmitObservationsIxData.
type submitObservationsInstructionWire struct {
	Discriminator uint8
	Data          submitObservationsIxDataWire
}

func (submitObservationsInstructionWire) wireLen() int { return submitObservationsInstructionLen }

func (submitObservationsInstructionWire) wireName() string {
	return "submit_observations instruction data"
}

// Token Bridge transfer payload, vaa.rs.

// TokenBridgeTransfer::LEN.
const tokenBridgeTransferLen = 133

// MAX_TRANSFER_PAYLOAD_LEN.
const maxTransferPayloadLen = 2000

// tokenBridgeTransferWire is TokenBridgeTransfer, the fixed head of a transfer payload.
type tokenBridgeTransferWire struct {
	Action         uint8
	Amount         [32]byte
	TokenAddress   [32]byte
	TokenChain     be16
	Recipient      [32]byte
	RecipientChain be16
	Fee            [32]byte
}

func (tokenBridgeTransferWire) wireLen() int { return tokenBridgeTransferLen }

func (tokenBridgeTransferWire) wireName() string { return "token bridge transfer" }

// PDA seed prefixes, constants/seeds.rs.

// PENDING_OBSERVATIONS_SEED_PREFIX.
var pendingObservationsSeedPrefix = []byte("pending")

// NOREPLAY_AUTHORITY_SEED_PREFIX.
var noreplayAuthoritySeedPrefix = []byte("noreplay_authority")

// ACCOUNT_SEED_PREFIX.
var balanceAccountSeedPrefix = []byte("account")

// CHAIN_REGISTRATION_SEED_PREFIX.
var chainRegistrationSeedPrefix = []byte("chain_registration")

// GUARDIAN_SET_SEED. The Core Bridge's own seed.
var guardianSetSeedPrefix = []byte("GuardianSet")

// GlobalAccountantError codes returned as ProgramError::Custom, error.rs.

// GlobalAccountantError::PayerMismatch.
const solanaErrPayerMismatch = 4

// GlobalAccountantError::AlreadyAccounted.
const solanaErrAlreadyAccounted = 7

// GlobalAccountantError::InvalidSignature.
const solanaErrInvalidSignature = 9

// GlobalAccountantError::InvalidGuardianIndex.
const solanaErrInvalidGuardianIndex = 10

// GlobalAccountantError::AlreadySigned.
const solanaErrAlreadySigned = 11

// GlobalAccountantError::ExpiredGuardianSet.
const solanaErrExpiredGuardianSet = 12

// GlobalAccountantError::MissingChainRegistration.
const solanaErrMissingChainRegistration = 19

// GlobalAccountantError::UnregisteredEmitter.
const solanaErrUnregisteredEmitter = 20
