// Code generated by svm/accountant/crates/go-codegen. DO NOT EDIT.

package accountant

// NttObservationFieldsAndDigest, ix_data.rs: the hashed record.

// Length of the hashed record.
const nttObservationFieldsLen = 117

// nttObservationFieldsWire is the tail of NttSubmitObservationsIxData from chain.
type nttObservationFieldsWire struct {
	Chain           be16
	Emitter         [32]byte
	Sequence        be64
	Sender          [32]byte
	RecipientChain  be16
	TrimmedDecimals uint8
	TrimmedAmount   be64
	VaaDigest       [32]byte
}

func (nttObservationFieldsWire) wireLen() int { return nttObservationFieldsLen }

func (nttObservationFieldsWire) wireName() string { return "ntt observation fields" }

// NTT submit_observations instruction, ix_data.rs.

// NttInstruction::SubmitObservations.
const nttSubmitObservationsDiscriminator = 0

// NttSubmitObservationsIxData::LEN.
const nttSubmitObservationsIxDataLen = 252

// One u8 discriminator plus the data.
const nttSubmitObservationsInstructionLen = 253

// nttSubmitObservationsIxDataWire is NttSubmitObservationsIxData.
type nttSubmitObservationsIxDataWire struct {
	GuardianSetIndex uint32
	GuardianIndex    uint8
	Signature        [65]byte
	TxIDLen          uint8
	TxID             [64]byte
	Fields           nttObservationFieldsWire
}

func (nttSubmitObservationsIxDataWire) wireLen() int { return nttSubmitObservationsIxDataLen }

func (nttSubmitObservationsIxDataWire) wireName() string {
	return "ntt submit_observations instruction data"
}

// nttSubmitObservationsInstructionWire is the discriminator and NttSubmitObservationsIxData.
type nttSubmitObservationsInstructionWire struct {
	Discriminator uint8
	Data          nttSubmitObservationsIxDataWire
}

func (nttSubmitObservationsInstructionWire) wireLen() int { return nttSubmitObservationsInstructionLen }

func (nttSubmitObservationsInstructionWire) wireName() string {
	return "ntt submit_observations instruction data"
}

// TransceiverHubLayout and TransceiverPeerLayout, state.rs.

// TransceiverHubLayout::LEN.
const transceiverHubLen = 70

// TransceiverHubLayout::TAG.
const transceiverHubTag = 6

// TransceiverPeerLayout::LEN.
const transceiverPeerLen = 70

// TransceiverPeerLayout::TAG.
const transceiverPeerTag = 7

// transceiverHubWire is TransceiverHubLayout.
type transceiverHubWire struct {
	Tag        uint8
	_          [1]byte
	Chain      uint16
	HubChain   uint16
	Address    [32]byte
	HubAddress [32]byte
}

func (transceiverHubWire) wireLen() int { return transceiverHubLen }

func (transceiverHubWire) wireName() string { return "transceiver hub account" }

// transceiverPeerWire is TransceiverPeerLayout.
type transceiverPeerWire struct {
	Tag         uint8
	_           [1]byte
	Chain       uint16
	DestChain   uint16
	Address     [32]byte
	PeerAddress [32]byte
}

func (transceiverPeerWire) wireLen() int { return transceiverPeerLen }

func (transceiverPeerWire) wireName() string { return "transceiver peer account" }

// PDA seed prefixes, constants/seeds.rs.

// TRANSCEIVER_HUB_SEED_PREFIX.
var transceiverHubSeedPrefix = []byte("transceiver_hub")

// TRANSCEIVER_PEER_SEED_PREFIX.
var transceiverPeerSeedPrefix = []byte("transceiver_peer")

// GlobalAccountantError codes the NTT submit path branches on, error.rs.

// GlobalAccountantError::InvalidInstructionData.
const solanaErrInvalidInstructionData = 1

// GlobalAccountantError::MalformedNttMessage.
const solanaErrMalformedNttMessage = 34

// GlobalAccountantError::MissingTransceiverHub.
const solanaErrMissingTransceiverHub = 39

// GlobalAccountantError::MissingSourcePeer.
const solanaErrMissingSourcePeer = 46

// GlobalAccountantError::MissingDestinationPeer.
const solanaErrMissingDestinationPeer = 47

// GlobalAccountantError::PeersNotCrossRegistered.
const solanaErrPeersNotCrossRegistered = 48
