// Code generated by svm/accountant/programs/global-accountant/tests/go_codegen.rs. DO NOT EDIT.

package accountant

// AccountantDigestLog, constants/log.rs.

// AccountantDigestLog::LEN.
const accountantDigestLogLen = 86

// ACCOUNTANT_DIGEST_LOG_TAG.
var accountantDigestLogTag = [8]byte{0x41, 0x43, 0x43, 0x44, 0x47, 0x53, 0x54, 0x00}

// Big-endian.
const accountantDigestLogChainOffset = 8

const accountantDigestLogEmitterOffset = 10

// Big-endian.
const accountantDigestLogSequenceOffset = 42

const accountantDigestLogDigestOffset = 50

// Little-endian.
const accountantDigestLogGuardianSetIndexOffset = 82

// PendingObservationsLayout, state.rs. Integers are little-endian.

// PendingObservationsLayout::LEN.
const pendingObservationsLen = 88

// PendingObservationsLayout::TAG.
const pendingObservationsTag = 1

// PendingObservationsLayout::MAX_GUARDIANS.
const pendingObservationsMaxGuardians = 128

// u32 words in the signature bitmap.
const pendingObservationsSignatureWords = 4

const pendingObservationsChainOffset = 2

const pendingObservationsGuardianSetIndexOffset = 4

const pendingObservationsSignaturesOffset = 8

const pendingObservationsContentDigestOffset = 24

const pendingObservationsPayerOffset = 56

// solana-noreplay bucket, constants/noreplay.rs.

// NoReplayBitmapAccount::LEN.
const noreplayBucketLen = 129

const noreplayBitmapOffset = 1

// NOREPLAY_BITS_PER_BUCKET.
const noreplayBitsPerBucket = 1024

// submit_observations instruction data, ix_data.rs. Offsets include the discriminator.

// One u8 discriminator.
const submitObservationsDispatchLen = 1

// Instruction::SubmitObservations.
const submitObservationsDiscriminator = 0

// SubmitObservationsIxData::LEN.
const submitObservationsIxDataLen = 278

// Little-endian.
const submitGuardianSetIndexOffset = 1

const submitGuardianIndexOffset = 5

const submitSignatureOffset = 6

// r ‖ s ‖ recovery_id.
const submitSignatureLen = 65

const submitTxIDLenOffset = 71

const submitTxIDOffset = 72

// Start of the hashed record.
const submitFieldsOffset = 136

// TxId, ix_data.rs.

// HASH_TX_ID_LEN.
const hashTxIDLen = 32

// SIGNATURE_TX_ID_LEN.
const signatureTxIDLen = 64

// ObservationFieldsAndDigest, ix_data.rs. Integers are big-endian.

// Length of the hashed record.
const observationFieldsLen = 143

const fieldsActionOffset = 0

const fieldsChainOffset = 1

const fieldsEmitterOffset = 3

const fieldsSequenceOffset = 35

const fieldsTokenChainOffset = 43

const fieldsTokenAddressOffset = 45

const fieldsRecipientChainOffset = 77

const fieldsAmountOffset = 79

const fieldsVaaDigestOffset = 111

// Token Bridge transfer payload, vaa.rs.

// TokenBridgeTransfer::LEN.
const tokenBridgeTransferLen = 133

// MAX_TRANSFER_PAYLOAD_LEN.
const maxTransferPayloadLen = 2000

// PDA seed prefixes, constants/seeds.rs.

// PENDING_OBSERVATIONS_SEED_PREFIX.
var pendingObservationsSeedPrefix = []byte("pending")

// NOREPLAY_AUTHORITY_SEED_PREFIX.
var noreplayAuthoritySeedPrefix = []byte("noreplay_authority")

// ACCOUNT_SEED_PREFIX.
var balanceAccountSeedPrefix = []byte("account")

// CHAIN_REGISTRATION_SEED_PREFIX.
var chainRegistrationSeedPrefix = []byte("chain_registration")

// GUARDIAN_SET_SEED. The Core Bridge's own seed.
var guardianSetSeedPrefix = []byte("GuardianSet")

// GlobalAccountantError codes returned as ProgramError::Custom, error.rs.

// GlobalAccountantError::PayerMismatch.
const solanaErrPayerMismatch = 4

// GlobalAccountantError::AlreadyAccounted.
const solanaErrAlreadyAccounted = 7

// GlobalAccountantError::InvalidSignature.
const solanaErrInvalidSignature = 9

// GlobalAccountantError::InvalidGuardianIndex.
const solanaErrInvalidGuardianIndex = 10

// GlobalAccountantError::AlreadySigned.
const solanaErrAlreadySigned = 11

// GlobalAccountantError::ExpiredGuardianSet.
const solanaErrExpiredGuardianSet = 12

// GlobalAccountantError::MissingChainRegistration.
const solanaErrMissingChainRegistration = 19

// GlobalAccountantError::UnregisteredEmitter.
const solanaErrUnregisteredEmitter = 20
