package canton

import (
	"context"
	"encoding/hex"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/certusone/wormhole/node/pkg/cantonclient"
	"github.com/certusone/wormhole/node/pkg/common"
	gossipv1 "github.com/certusone/wormhole/node/pkg/proto/gossip/v1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wormhole-foundation/wormhole/sdk/vaa"
	"go.uber.org/zap"
)

// Emitter key components and the address they must derive to. These are the
// shared cross-language vector generated by
// node/pkg/cantonclient/vectorgen_test.go (TestGenerateAddressVectors) and
// asserted on the Daml side by Test.TestCore:testAddressVector — DO NOT edit one
// side without regenerating and updating both.
const (
	sampleRegistrar   = "vector-operator::1220deadbeef"
	sampleOwner       = "vector-owner::1220cafebabe"
	sampleEmitterID   = uint64(7)
	sampleWantAddrHex = "45ae8886d1c165b071d3b1202fe81ebedc39f61a6a91a1d13140eb64857f3f2b"
)

// wantAddr is the emitter address the watcher must derive from the sample key.
func wantAddr(t *testing.T) vaa.Address {
	t.Helper()
	b, err := hex.DecodeString(sampleWantAddrHex)
	require.NoError(t, err)
	var a vaa.Address
	copy(a[:], b)
	return a
}

// fakeClient is a programmable CantonClient that lets a test drive the
// subscription (push events, fail it) so the Run loop is testable without a
// live participant.
type fakeClient struct {
	mu sync.Mutex

	ledgerEnd      int64
	ledgerEndErr   error
	ledgerEndCalls int

	byOffset     map[int64]cantonclient.CantonTransaction
	getUpdateErr error

	subCalls   int
	subBegin   int64                   // beginExclusive of the latest SubscribeUpdates
	subTmpl    cantonclient.TemplateID // template filter of the latest SubscribeUpdates
	subChoice  string                  // choice name of the latest SubscribeUpdates
	out        chan<- cantonclient.CantonMessageEvent
	sub        *cantonclient.Subscription
	subscribed chan struct{} // signaled on each SubscribeUpdates
}

func newFakeClient() *fakeClient {
	return &fakeClient{
		byOffset:   map[int64]cantonclient.CantonTransaction{},
		subscribed: make(chan struct{}, 16),
	}
}

func (f *fakeClient) GetLedgerEnd(_ context.Context) (int64, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.ledgerEndCalls++
	if f.ledgerEndErr != nil {
		return 0, f.ledgerEndErr
	}
	return f.ledgerEnd, nil
}

func (f *fakeClient) SubscribeUpdates(_ context.Context, begin int64, tmpl cantonclient.TemplateID, choice string, out chan<- cantonclient.CantonMessageEvent) (*cantonclient.Subscription, error) {
	f.mu.Lock()
	f.subCalls++
	f.subBegin = begin
	f.subTmpl = tmpl
	f.subChoice = choice
	f.out = out
	sub := cantonclient.NewSubscription(func() {})
	f.sub = sub
	subscribed := f.subscribed
	f.mu.Unlock()
	if subscribed != nil {
		select {
		case subscribed <- struct{}{}:
		default:
		}
	}
	return sub, nil
}

func (f *fakeClient) GetUpdateByOffset(_ context.Context, offset int64, _ cantonclient.TemplateID, _ string) (cantonclient.CantonTransaction, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.getUpdateErr != nil {
		return cantonclient.CantonTransaction{}, f.getUpdateErr
	}
	// Match the real client: an offset with no matching transaction is an error,
	// not an empty result.
	tx, ok := f.byOffset[offset]
	if !ok {
		return cantonclient.CantonTransaction{}, fmt.Errorf("GetUpdateByOffset(%d): not a transaction", offset)
	}
	return tx, nil
}

func (f *fakeClient) Close() error { return nil }

// waitSubscribed blocks until the data pump has (re)subscribed, so the stream
// channel is captured before the test pushes events.
func (f *fakeClient) waitSubscribed(t *testing.T) {
	t.Helper()
	select {
	case <-f.subscribed:
	case <-time.After(5 * time.Second):
		t.Fatal("watcher never subscribed")
	}
}

func (f *fakeClient) pushEvent(ev cantonclient.CantonMessageEvent) {
	f.mu.Lock()
	out := f.out
	f.mu.Unlock()
	out <- ev
}

func (f *fakeClient) failSubscription(err error) {
	f.mu.Lock()
	sub := f.sub
	f.mu.Unlock()
	sub.Fail(err)
}

func (f *fakeClient) subscribeCount() int {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.subCalls
}

// subscribeArgs returns the (beginExclusive, template, choice) of the latest
// SubscribeUpdates call, so a test can assert the watcher streams from the
// right offset with the right filter.
func (f *fakeClient) subscribeArgs() (int64, cantonclient.TemplateID, string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.subBegin, f.subTmpl, f.subChoice
}

func testWatcher(msgC chan<- *common.MessagePublication) *Watcher {
	return NewWatcher("canton:5011", "pkg123", "Operator::ns", AuthConfig{}, true, msgC, make(chan *gossipv1.ObservationRequest))
}

func TestProcessMessageBuildsObservation(t *testing.T) {
	msgC := make(chan *common.MessagePublication, 1)
	w := testWatcher(msgC)

	ts := time.Unix(1_700_000_000, 0).UTC()
	w.processMessage(zap.NewNop(), cantonclient.CantonMessageEvent{
		Offset:      42,
		UpdateID:    "update-1",
		EffectiveAt: ts,
		Message: cantonclient.CantonMessage{
			Registrar:        sampleRegistrar,
			Owner:            sampleOwner,
			EmitterID:        sampleEmitterID,
			Sequence:         7,
			Nonce:            99,
			ConsistencyLevel: 0,
			Payload:          []byte{0xde, 0xad},
		},
	}, false)

	got := <-msgC
	assert.Equal(t, vaa.ChainIDCanton, got.EmitterChain)
	assert.Equal(t, uint64(7), got.Sequence)
	assert.Equal(t, uint32(99), got.Nonce)
	assert.Equal(t, ts, got.Timestamp)
	assert.Equal(t, []byte{0xde, 0xad}, got.Payload)
	assert.False(t, got.IsReobservation)
	// TxID is the offset encoded as 32 big-endian bytes.
	assert.Equal(t, cantonclient.OffsetToTxID(42), got.TxID)
	// Emitter address is keccak256(tag ‖ registrar ‖ owner ‖ emitterId).
	assert.Equal(t, wantAddr(t), got.EmitterAddress)
}

func TestProcessMessageDropsMissingKeyParty(t *testing.T) {
	for name, msg := range map[string]cantonclient.CantonMessage{
		"empty registrar": {Registrar: "", Owner: sampleOwner, EmitterID: 0},
		"empty owner":     {Registrar: sampleRegistrar, Owner: "", EmitterID: 0},
	} {
		t.Run(name, func(t *testing.T) {
			msgC := make(chan *common.MessagePublication, 1)
			w := testWatcher(msgC)

			w.processMessage(zap.NewNop(), cantonclient.CantonMessageEvent{
				Offset:      1,
				EffectiveAt: time.Unix(1, 0),
				Message:     msg,
			}, false)

			select {
			case <-msgC:
				t.Fatal("expected no observation for a message missing an emitter key party")
			default:
			}
		})
	}
}

// TestDeriveEmitterAddressMatchesVector pins the Go encoder against the shared
// cross-language vector and checks that each key component affects the address,
// including that the length prefixes disambiguate the two variable-length parts.
func TestDeriveEmitterAddressMatchesVector(t *testing.T) {
	assert.Equal(t, wantAddr(t), deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID))

	base := deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID)
	assert.NotEqual(t, base, deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID+1), "id must matter")
	assert.NotEqual(t, base, deriveEmitterAddress(sampleOwner, sampleRegistrar, sampleEmitterID), "swapping parties must matter")

	// Without length prefixes, ("a","bc") and ("ab","c") would collide.
	assert.NotEqual(t,
		deriveEmitterAddress("a", "bc", 0),
		deriveEmitterAddress("ab", "c", 0),
		"length prefixes must disambiguate the party boundary")
}

func TestHandleReobservation(t *testing.T) {
	msgC := make(chan *common.MessagePublication, 1)
	w := testWatcher(msgC)

	const offset int64 = 1234
	client := &fakeClient{
		byOffset: map[int64]cantonclient.CantonTransaction{
			offset: {
				Offset:      offset,
				UpdateID:    "update-reobs",
				EffectiveAt: time.Unix(1_700_000_001, 0).UTC(),
				Messages: []cantonclient.CantonMessage{{
					Registrar: sampleRegistrar,
					Owner:     sampleOwner,
					EmitterID: sampleEmitterID,
					Sequence:  3,
					Payload:   []byte{0x01},
				}},
			},
		},
	}

	w.handleReobservation(context.Background(), zap.NewNop(), client, &gossipv1.ObservationRequest{
		ChainId: uint32(vaa.ChainIDCanton),
		TxHash:  cantonclient.OffsetToTxID(offset),
	})

	got := <-msgC
	assert.True(t, got.IsReobservation)
	assert.Equal(t, uint64(3), got.Sequence)
	assert.Equal(t, cantonclient.OffsetToTxID(offset), got.TxID)
	assert.Equal(t, wantAddr(t), got.EmitterAddress)
}

func TestHandleReobservationWrongChainPanics(t *testing.T) {
	w := testWatcher(make(chan *common.MessagePublication, 1))
	require.Panics(t, func() {
		w.handleReobservation(context.Background(), zap.NewNop(), &fakeClient{}, &gossipv1.ObservationRequest{
			ChainId: uint32(vaa.ChainIDEthereum),
			TxHash:  cantonclient.OffsetToTxID(1),
		})
	})
}
