package canton

import (
	"context"
	"encoding/hex"
	"testing"
	"time"

	"github.com/certusone/wormhole/node/pkg/cantonclient"
	"github.com/certusone/wormhole/node/pkg/common"
	gossipv1 "github.com/certusone/wormhole/node/pkg/proto/gossip/v1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wormhole-foundation/wormhole/sdk/vaa"
	"go.uber.org/zap"
)

// Emitter key components and the address they must derive to. These are the
// shared cross-language vector generated by
// node/pkg/cantonclient/vectorgen_test.go (TestGenerateAddressVectors) and
// asserted on the Daml side by Test.TestCore:testAddressVector — DO NOT edit one
// side without regenerating and updating both.
const (
	sampleRegistrar   = "vector-operator::1220deadbeef"
	sampleOwner       = "vector-owner::1220cafebabe"
	sampleEmitterID   = uint64(7)
	sampleWantAddrHex = "45ae8886d1c165b071d3b1202fe81ebedc39f61a6a91a1d13140eb64857f3f2b"
)

// wantAddr is the emitter address the watcher must derive from the sample key.
func wantAddr(t *testing.T) vaa.Address {
	t.Helper()
	b, err := hex.DecodeString(sampleWantAddrHex)
	require.NoError(t, err)
	var a vaa.Address
	copy(a[:], b)
	return a
}

// fakeClient is a CantonClient that returns canned data for tests.
type fakeClient struct {
	ledgerEnd   int64
	byOffset    map[int64]cantonclient.CantonTransaction
	closeCalled bool
}

func (f *fakeClient) GetLedgerEnd(_ context.Context) (int64, error) { return f.ledgerEnd, nil }
func (f *fakeClient) SubscribeUpdates(_ context.Context, _ int64, _ cantonclient.TemplateID, _ string, _ chan<- cantonclient.CantonMessageEvent) (*cantonclient.Subscription, error) {
	return cantonclient.NewSubscription(func() {}), nil
}
func (f *fakeClient) GetUpdateByOffset(_ context.Context, offset int64, _ cantonclient.TemplateID, _ string) (cantonclient.CantonTransaction, error) {
	return f.byOffset[offset], nil
}
func (f *fakeClient) Close() error { f.closeCalled = true; return nil }

func testWatcher(msgC chan<- *common.MessagePublication) *Watcher {
	return NewWatcher("canton:5011", "pkg123", "Operator::ns", true, msgC, make(chan *gossipv1.ObservationRequest))
}

func TestProcessMessageBuildsObservation(t *testing.T) {
	msgC := make(chan *common.MessagePublication, 1)
	w := testWatcher(msgC)

	ts := time.Unix(1_700_000_000, 0).UTC()
	w.processMessage(zap.NewNop(), cantonclient.CantonMessageEvent{
		Offset:      42,
		UpdateID:    "update-1",
		EffectiveAt: ts,
		Message: cantonclient.CantonMessage{
			Registrar:        sampleRegistrar,
			Owner:            sampleOwner,
			EmitterID:        sampleEmitterID,
			Sequence:         7,
			Nonce:            99,
			ConsistencyLevel: 0,
			Payload:          []byte{0xde, 0xad},
		},
	}, false)

	got := <-msgC
	assert.Equal(t, vaa.ChainIDCanton, got.EmitterChain)
	assert.Equal(t, uint64(7), got.Sequence)
	assert.Equal(t, uint32(99), got.Nonce)
	assert.Equal(t, ts, got.Timestamp)
	assert.Equal(t, []byte{0xde, 0xad}, got.Payload)
	assert.False(t, got.IsReobservation)
	// TxID is the offset encoded as 32 big-endian bytes.
	assert.Equal(t, cantonclient.OffsetToTxID(42), got.TxID)
	// Emitter address is keccak256(tag ‖ registrar ‖ owner ‖ emitterId).
	assert.Equal(t, wantAddr(t), got.EmitterAddress)
}

func TestProcessMessageDropsMissingKeyParty(t *testing.T) {
	for name, msg := range map[string]cantonclient.CantonMessage{
		"empty registrar": {Registrar: "", Owner: sampleOwner, EmitterID: 0},
		"empty owner":     {Registrar: sampleRegistrar, Owner: "", EmitterID: 0},
	} {
		t.Run(name, func(t *testing.T) {
			msgC := make(chan *common.MessagePublication, 1)
			w := testWatcher(msgC)

			w.processMessage(zap.NewNop(), cantonclient.CantonMessageEvent{
				Offset:      1,
				EffectiveAt: time.Unix(1, 0),
				Message:     msg,
			}, false)

			select {
			case <-msgC:
				t.Fatal("expected no observation for a message missing an emitter key party")
			default:
			}
		})
	}
}

// TestDeriveEmitterAddressMatchesVector pins the Go encoder against the shared
// cross-language vector and checks that each key component affects the address,
// including that the length prefixes disambiguate the two variable-length parts.
func TestDeriveEmitterAddressMatchesVector(t *testing.T) {
	assert.Equal(t, wantAddr(t), deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID))

	base := deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID)
	assert.NotEqual(t, base, deriveEmitterAddress(sampleRegistrar, sampleOwner, sampleEmitterID+1), "id must matter")
	assert.NotEqual(t, base, deriveEmitterAddress(sampleOwner, sampleRegistrar, sampleEmitterID), "swapping parties must matter")

	// Without length prefixes, ("a","bc") and ("ab","c") would collide.
	assert.NotEqual(t,
		deriveEmitterAddress("a", "bc", 0),
		deriveEmitterAddress("ab", "c", 0),
		"length prefixes must disambiguate the party boundary")
}

func TestHandleReobservation(t *testing.T) {
	msgC := make(chan *common.MessagePublication, 1)
	w := testWatcher(msgC)

	const offset int64 = 1234
	client := &fakeClient{
		byOffset: map[int64]cantonclient.CantonTransaction{
			offset: {
				Offset:      offset,
				UpdateID:    "update-reobs",
				EffectiveAt: time.Unix(1_700_000_001, 0).UTC(),
				Messages: []cantonclient.CantonMessage{{
					Registrar: sampleRegistrar,
					Owner:     sampleOwner,
					EmitterID: sampleEmitterID,
					Sequence:  3,
					Payload:   []byte{0x01},
				}},
			},
		},
	}

	w.handleReobservation(context.Background(), zap.NewNop(), client, &gossipv1.ObservationRequest{
		ChainId: uint32(vaa.ChainIDCanton),
		TxHash:  cantonclient.OffsetToTxID(offset),
	})

	got := <-msgC
	assert.True(t, got.IsReobservation)
	assert.Equal(t, uint64(3), got.Sequence)
	assert.Equal(t, cantonclient.OffsetToTxID(offset), got.TxID)
	assert.Equal(t, wantAddr(t), got.EmitterAddress)
}

func TestHandleReobservationWrongChainPanics(t *testing.T) {
	w := testWatcher(make(chan *common.MessagePublication, 1))
	require.Panics(t, func() {
		w.handleReobservation(context.Background(), zap.NewNop(), &fakeClient{}, &gossipv1.ObservationRequest{
			ChainId: uint32(vaa.ChainIDEthereum),
			TxHash:  cantonclient.OffsetToTxID(1),
		})
	})
}
